//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirebaseNotificationSender.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_accounts()
        {
            this.trip_request = new HashSet<trip_request>();
            this.trip_share = new HashSet<trip_share>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> register_time { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> gender_id { get; set; }
        public string id_no { get; set; }
        public string driver_license_no { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual sec_users sec_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip_request> trip_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trip_share> trip_share { get; set; }
    }
}
