//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class chari80_dbEntities : DbContext
    {
        public chari80_dbEntities()
            : base("name=chari80_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sec_access_right> sec_access_right { get; set; }
        public virtual DbSet<sec_mobile_verify> sec_mobile_verify { get; set; }
        public virtual DbSet<sec_roles> sec_roles { get; set; }
        public virtual DbSet<sec_sessions> sec_sessions { get; set; }
        public virtual DbSet<sec_users> sec_users { get; set; }
        public virtual DbSet<sec_users_roles> sec_users_roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_accounts> tbl_accounts { get; set; }
        public virtual DbSet<tbl_cities> tbl_cities { get; set; }
        public virtual DbSet<tbl_countries> tbl_countries { get; set; }
        public virtual DbSet<tbl_drivers_vehicles_rel> tbl_drivers_vehicles_rel { get; set; }
        public virtual DbSet<tbl_genders> tbl_genders { get; set; }
        public virtual DbSet<tbl_images> tbl_images { get; set; }
        public virtual DbSet<tbl_setting> tbl_setting { get; set; }
        public virtual DbSet<tbl_setting_types> tbl_setting_types { get; set; }
        public virtual DbSet<tbl_vehicles> tbl_vehicles { get; set; }
        public virtual DbSet<trip_book> trip_book { get; set; }
        public virtual DbSet<trip_request> trip_request { get; set; }
        public virtual DbSet<trip_request_details> trip_request_details { get; set; }
        public virtual DbSet<trip_share> trip_share { get; set; }
        public virtual DbSet<trip_share_details> trip_share_details { get; set; }
        public virtual DbSet<trip_types> trip_types { get; set; }
    
        [DbFunction("chari80_dbEntities", "parseJSON")]
        public virtual IQueryable<parseJSON_Result> parseJSON(string jSON)
        {
            var jSONParameter = jSON != null ?
                new ObjectParameter("JSON", jSON) :
                new ObjectParameter("JSON", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<parseJSON_Result>("[chari80_dbEntities].[parseJSON](@JSON)", jSONParameter);
        }
    }
}
