//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chari80.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sec_access_right> sec_access_right { get; set; }
        public virtual DbSet<sec_mobile_verify> sec_mobile_verify { get; set; }
        public virtual DbSet<sec_roles> sec_roles { get; set; }
        public virtual DbSet<sec_sessions> sec_sessions { get; set; }
        public virtual DbSet<sec_users> sec_users { get; set; }
        public virtual DbSet<sec_users_roles> sec_users_roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_cities> tbl_cities { get; set; }
        public virtual DbSet<tbl_countries> tbl_countries { get; set; }
        public virtual DbSet<tbl_genders> tbl_genders { get; set; }
        public virtual DbSet<tbl_images> tbl_images { get; set; }
        public virtual DbSet<tbl_setting> tbl_setting { get; set; }
        public virtual DbSet<tbl_setting_types> tbl_setting_types { get; set; }
        public virtual DbSet<tbl_accounts> tbl_accounts { get; set; }
        public virtual DbSet<tbl_drivers_vehicles_rel> tbl_drivers_vehicles_rel { get; set; }
        public virtual DbSet<tbl_vehicles> tbl_vehicles { get; set; }
    }
}
